### ISSUE TITLE
Some very wrong results 

### ISSUE THREAD

**Issue by Rob-bb** [juvenius/du_ez_scanner#2]
Hi, sometimes I get hugely wrong results. The destination is 5.6km away, but all readings were taken in the chart circled in blue here. 

This happens often but not always, usually it is very accurate, within 20 or 30 meters of the actual ore

![image](https://user-images.githubusercontent.com/3431318/101996236-5dba8d00-3d35-11eb-8dc6-5aac2afa062b.png)

**Comment by juvenius** [comment]
hey there thx for the feedback ROB, 

It should never give a result so far unless you took points very far apart, so something is off there for sure. Can you send me the location where that happen? we are testing the script on different places to see if we can replicate the issue.

**Comment by Rob-bb** [comment]
Hi, I have another one, I took readings in the blue range again, yet the scanner says I am 30m away and the location is 370m away.  Also weirdly I am having trouble with it when searching for Quartz, not sure that is a bug, I suspect it is a lot of small quartz nodes near each other, in this picture I had already found a node where the green circle is after twice trying and finding the destination was around 100m wrong (white circle was when I was at destination previously).  So I think that is me not picking up a change of node in the scanner 

I have had some others in the 1 to 3 km range away

  This is the hex tile I am in  ::pos{0,2,39.5450,-137.4756,-294.7797}


![image](https://user-images.githubusercontent.com/3431318/102003013-2533a700-3d67-11eb-82f2-59c2b0c52100.png)

**Comment by juvenius** [comment]
will look in to it, thx.
